# Generated by Django 2.1 on 2018-11-14 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calvin', '0007_auto_20181114_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
