# Generated by Django 2.1 on 2018-11-18 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calvin', '0010_auto_20181118_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='video',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
