# Generated by Django 2.1 on 2018-11-18 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calvin', '0013_auto_20181118_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
