# Generated by Django 2.1 on 2018-11-20 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calvin', '0014_auto_20181118_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
