# Generated by Django 2.1 on 2018-11-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calvin', '0016_page_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='file',
            field=models.URLField(blank=True, null=True),
        ),
    ]
